/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CiscoCodePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  promptColor: "#008080",
  commandColor: "#ff8c00",
  interfaceColor: "#003153",
  ipColor: "#656598",
  numberColor: "#aa78aa",
  commentColor: "#6a9955",
  fileColor: "#ff69b4",
  textColor: "var(--text-normal)",
  commands: [
    "access",
    "access-class",
    "access-list",
    "access-lists",
    "active",
    "add",
    "address",
    "address-table",
    "all",
    "allowed",
    "allow-untrusted",
    "arp",
    "arp-cache",
    "any",
    "ascii",
    "authentication-retries",
    "auto",
    "binding",
    "boot",
    "brief",
    "broadcast",
    "banner",
    "both",
    "bpduguard",
    "buffered",
    "cdp",
    "clear",
    "client",
    "clock",
    "configure",
    "configured",
    "conflict",
    "connect",
    "copy",
    "counters",
    "crypto",
    "channel-group",
    "channel-protocol",
    "cisco-phone",
    "client-id",
    "community",
    "console",
    "cos",
    "database",
    "debug",
    "delete",
    "detail",
    "dhcp",
    "dir",
    "disable",
    "disconnect",
    "domain",
    "dtp",
    "dynamic",
    "databits",
    "datetime",
    "debugging",
    "default",
    "default-gateway",
    "default-router",
    "deny",
    "description",
    "desirable",
    "destination",
    "device",
    "dns-server",
    "do",
    "domain-lookup",
    "domain-name",
    "dscp",
    "dst-ip",
    "dst-mac",
    "duplex",
    "enable",
    "entry",
    "erase",
    "etherchannel",
    "event",
    "events",
    "end",
    "exit",
    "even",
    "except",
    "excluded-address",
    "exec",
    "exec-timeout",
    "extend",
    "extended",
    "flowcontrol",
    "ftp",
    "full",
    "generate",
    "guard",
    "history",
    "hosts",
    "half",
    "hardware",
    "hardware-address",
    "host",
    "hostname",
    "icmp",
    "id",
    "inconsistentports",
    "information",
    "interface",
    "ip",
    "in",
    "key",
    "lease",
    "lldp",
    "load-balance",
    "local",
    "logging",
    "logout",
    "lacp",
    "level",
    "limit",
    "line",
    "link-type",
    "load-balance",
    "log",
    "login",
    "lookup",
    "mac",
    "mac-address-table",
    "memory",
    "mls",
    "mode",
    "monitor",
    "more",
    "mypubkey",
    "mac-address",
    "mark",
    "maximum",
    "mdix",
    "motd",
    "motd-banner",
    "msec",
    "name",
    "neighbors",
    "no",
    "name-server",
    "native",
    "network",
    "none",
    "nonegotiate",
    "odd",
    "on",
    "option",
    "out",
    "output",
    "packet",
    "packets",
    "password",
    "ping",
    "pool",
    "port-channel",
    "port-security",
    "portfast",
    "privilege",
    "processes",
    "protocol",
    "pagp",
    "parity",
    "passive",
    "password-encryption",
    "permit",
    "point-to-point",
    "portfast",
    "port-priority",
    "prefer",
    "primary",
    "priority",
    "protect",
    "pvst",
    "qos",
    "range",
    "reload",
    "remote",
    "resume",
    "rsa",
    "rapid-pvst",
    "rate",
    "receive",
    "relay",
    "remark",
    "remove",
    "reset",
    "restrict",
    "ro",
    "root",
    "router",
    "run",
    "rw",
    "rx",
    "sdm",
    "server",
    "session",
    "sessions",
    "set",
    "setup",
    "show",
    "size",
    "snmp",
    "snooping",
    "spanning-tree",
    "ssh",
    "static",
    "status",
    "sticky",
    "storm-control",
    "summary",
    "sw-vlan",
    "secondary",
    "secret",
    "service",
    "shutdown",
    "snmp-server",
    "software",
    "source",
    "space",
    "speed",
    "src-dst-ip",
    "src-dst-mac",
    "src-ip",
    "src-mac",
    "standard",
    "stopbits",
    "subscriber-id",
    "switchport",
    "synchronous",
    "system",
    "table",
    "tcp",
    "tech-support",
    "telnet",
    "terminal",
    "totals",
    "traceroute",
    "transparent",
    "trusted-sources",
    "time-out",
    "timestamps",
    "timezone",
    "transmit",
    "transport",
    "trap",
    "trunk",
    "trust",
    "trust-all",
    "tx",
    "tx-ring-limit",
    "use",
    "users",
    "username",
    "v2-mode",
    "verify ",
    "version",
    "vlan",
    "vtp",
    "violation",
    "voice",
    "write",
    "write-delay",
    "zeroize",
    "?"
  ],
  interfaces: [
    "FastEthernet",
    "GigabitEthernet",
    "TenGigabitEthernet",
    "Serial",
    "Ethernet",
    "Loopback",
    "Vlan",
    "Port-channel",
    "Tunnel"
  ],
  files: [
    "flash:",
    "ftp:",
    "tftp:",
    "nvram:",
    "running-config",
    "startup-config"
  ],
  debugMode: false,
  lineNumbers: true,
  customCSS: ""
};
var RuleEngine = class {
  constructor(settings) {
    this.settings = settings;
    this.compileRules();
  }
  compileRules() {
    try {
      this.promptRegex = /^(switch(?:\(config(?:-(?:if|vlan|line|route))?\))?[>#])/;
      const escapedCommands = this.settings.commands.filter((c) => c && c.trim()).map((c) => c.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).sort((a, b) => b.length - a.length);
      if (escapedCommands.length > 0) {
        this.commandRegex = new RegExp(`\\b(${escapedCommands.join("|")})\\b`, "i");
      } else {
        this.commandRegex = /(?!)/;
      }
      const escapedInterfaces = this.settings.interfaces.filter((i) => i && i.trim()).map((i) => i.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
      if (escapedInterfaces.length > 0) {
        this.interfaceRegex = new RegExp(`\\b(${escapedInterfaces})\\d*(?:/\\d+)*(?:\\.\\d+)?\\b`, "i");
      } else {
        this.interfaceRegex = /(?!)/;
      }
      this.ipRegex = /\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b/;
      this.numberRegex = /\b\d+(?:\/\d+)*\b/;
      this.commentRegex = /^!.*$/;
      const escapedFiles = this.settings.files.filter((f) => f && f.trim()).map((f) => f.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
      if (escapedFiles.length > 0) {
        this.fileRegex = new RegExp(`\\b(${escapedFiles})\\b`, "i");
      } else {
        this.fileRegex = /(?!)/;
      }
    } catch (error) {
      console.error("Error compiling rules:", error);
    }
  }
  // 安全的匹配方法
  safeMatchAll(regex, line, matches, className, priority) {
    try {
      const safeRegex = new RegExp(regex.source, regex.flags.includes("g") ? regex.flags : regex.flags + "g");
      let match;
      let count = 0;
      const MAX_MATCHES = 50;
      while ((match = safeRegex.exec(line)) !== null && count < MAX_MATCHES) {
        matches.push({
          index: match.index,
          length: match[0].length,
          className,
          priority
        });
        count++;
        if (match[0].length === 0)
          break;
      }
    } catch (error) {
      console.error(`Error matching ${className}:`, error);
    }
  }
  findMatches(line) {
    if (!line || line.length > 5e3) {
      return [];
    }
    const matches = [];
    try {
      if (this.commentRegex.test(line)) {
        const match = this.commentRegex.exec(line);
        if (match && match[0]) {
          matches.push({
            index: match.index,
            length: match[0].length,
            className: "cisco-comment",
            priority: 100
          });
        }
        return matches;
      }
      this.safeMatchAll(this.promptRegex, line, matches, "cisco-prompt", 95);
      this.safeMatchAll(this.ipRegex, line, matches, "cisco-ip", 90);
      this.safeMatchAll(this.interfaceRegex, line, matches, "cisco-interface", 85);
      this.safeMatchAll(this.commandRegex, line, matches, "cisco-command", 80);
      this.safeMatchAll(this.fileRegex, line, matches, "cisco-file", 75);
      this.safeMatchAll(this.numberRegex, line, matches, "cisco-number", 70);
    } catch (error) {
      console.error("Error finding matches:", error);
      return [];
    }
    if (matches.length === 0)
      return [];
    matches.sort((a, b) => a.index - b.index);
    return this.mergeOverlapping(matches);
  }
  mergeOverlapping(matches) {
    if (matches.length <= 1)
      return matches;
    const merged = [];
    for (const match of matches) {
      const last = merged[merged.length - 1];
      if (!last) {
        merged.push(match);
        continue;
      }
      const lastEnd = last.index + last.length;
      if (match.index >= lastEnd) {
        merged.push(match);
      } else if (match.priority > last.priority) {
        merged[merged.length - 1] = match;
      }
    }
    return merged;
  }
  updateSettings(settings) {
    this.settings = settings;
    this.compileRules();
  }
};
var HighlightProcessor = class {
  constructor(settings) {
    this.settings = settings;
    this.ruleEngine = new RuleEngine(settings);
  }
  processLine(line) {
    try {
      if (!line) {
        return '<span class="cisco-text"> </span>';
      }
      if (line.length > 5e3) {
        return `<span class="cisco-text">${this.escapeHtml(line.substring(0, 5e3))}...</span>`;
      }
      const matches = this.ruleEngine.findMatches(line);
      if (matches.length === 0) {
        return `<span class="cisco-text">${this.escapeHtml(line)}</span>`;
      }
      let result = "";
      let lastIndex = 0;
      for (const match of matches) {
        if (match.index > lastIndex) {
          const text = line.substring(lastIndex, match.index);
          if (text) {
            result += `<span class="cisco-text">${this.escapeHtml(text)}</span>`;
          }
        }
        const highlighted = line.substr(match.index, match.length);
        result += `<span class="${match.className}">${this.escapeHtml(highlighted)}</span>`;
        lastIndex = match.index + match.length;
      }
      if (lastIndex < line.length) {
        const text = line.substring(lastIndex);
        result += `<span class="cisco-text">${this.escapeHtml(text)}</span>`;
      }
      return result;
    } catch (error) {
      console.error("Error processing line:", error);
      return `<span class="cisco-text">${this.escapeHtml(line)}</span>`;
    }
  }
  escapeHtml(text) {
    if (!text)
      return "";
    const div = document.createElement("div");
    div.textContent = text;
    return div.innerHTML;
  }
  updateSettings(settings) {
    this.settings = settings;
    this.ruleEngine.updateSettings(settings);
  }
  generateCSS() {
    let css = ":root {\n";
    css += `  --cisco-prompt: ${this.settings.promptColor};
`;
    css += `  --cisco-command: ${this.settings.commandColor};
`;
    css += `  --cisco-interface: ${this.settings.interfaceColor};
`;
    css += `  --cisco-ip: ${this.settings.ipColor};
`;
    css += `  --cisco-number: ${this.settings.numberColor};
`;
    css += `  --cisco-comment: ${this.settings.commentColor};
`;
    css += `  --cisco-file: ${this.settings.fileColor};
`;
    css += `  --cisco-text: ${this.settings.textColor};
`;
    css += "}\n\n";
    if (this.settings.customCSS) {
      css += "/* Custom CSS */\n";
      css += this.settings.customCSS;
    }
    return css;
  }
};
var CiscoSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Cisco Code Highlighter Settings" });
    containerEl.createEl("h3", { text: "Colors" });
    this.addColorSetting("Command Prompt", "promptColor", "e.g., Switch>");
    this.addColorSetting("Commands", "commandColor", "e.g., enable, configure");
    this.addColorSetting("Interfaces", "interfaceColor", "e.g., GigabitEthernet0/1");
    this.addColorSetting("IP Addresses", "ipColor", "e.g., 192.168.1.1");
    this.addColorSetting("Numbers", "numberColor", "e.g., 255, 0/1");
    this.addColorSetting("Comments", "commentColor", "Lines starting with !");
    this.addColorSetting("Files", "fileColor", "e.g., running-config");
    this.addColorSetting("Text", "textColor", "Default text color");
    containerEl.createEl("h3", { text: "Keywords" });
    this.addKeywordManager("Commands", "commands");
    this.addKeywordManager("Interfaces", "interfaces");
    this.addKeywordManager("Files", "files");
    containerEl.createEl("h3", { text: "Display" });
    new import_obsidian.Setting(containerEl).setName("Show line numbers").setDesc("Display line numbers on the left side").addToggle((toggle) => toggle.setValue(this.plugin.settings.lineNumbers).onChange(async (value) => {
      this.plugin.settings.lineNumbers = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Advanced" });
    new import_obsidian.Setting(containerEl).setName("Debug mode").setDesc("Log processing information to console").addToggle((toggle) => toggle.setValue(this.plugin.settings.debugMode).onChange(async (value) => {
      this.plugin.settings.debugMode = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Custom CSS").setDesc("Add your own CSS rules to override styles").addTextArea((textarea) => textarea.setValue(this.plugin.settings.customCSS).onChange(async (value) => {
      this.plugin.settings.customCSS = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).addButton((button) => button.setButtonText("Reset to Defaults").setWarning().onClick(async () => {
      this.plugin.settings = JSON.parse(JSON.stringify(DEFAULT_SETTINGS));
      await this.plugin.saveSettings();
      this.display();
      new import_obsidian.Notice("Settings reset to defaults");
    })).addButton((button) => button.setButtonText("Export Settings").onClick(async () => {
      await navigator.clipboard.writeText(
        JSON.stringify(this.plugin.settings, null, 2)
      );
      new import_obsidian.Notice("Settings copied to clipboard");
    }));
  }
  addColorSetting(name, key, desc) {
    new import_obsidian.Setting(this.containerEl).setName(name).setDesc(desc).addColorPicker((color) => color.setValue(this.plugin.settings[key]).onChange(async (value) => {
      this.plugin.settings[key] = value;
      await this.plugin.saveSettings();
    }));
  }
  addKeywordManager(name, key) {
    const keywords = this.plugin.settings[key];
    const container = this.containerEl.createDiv();
    new import_obsidian.Setting(container).setName(name).setDesc("Press Enter or click Add to add keywords").addText((text) => text.setPlaceholder("New keyword...").onChange(() => {
    })).addButton((button) => button.setButtonText("Add").setCta().onClick(async () => {
      const input = container.querySelector('input[placeholder="New keyword..."]');
      if ((input == null ? void 0 : input.value) && !keywords.includes(input.value)) {
        keywords.push(input.value);
        await this.plugin.saveSettings();
        this.display();
      }
    }));
    const tagContainer = container.createDiv({ cls: "cisco-keyword-tags" });
    keywords.forEach((keyword, index) => {
      const tag = tagContainer.createSpan({ cls: "cisco-keyword-tag", text: keyword });
      tag.createEl("button", { text: "\xD7" }).addEventListener("click", async () => {
        keywords.splice(index, 1);
        await this.plugin.saveSettings();
        this.display();
      });
    });
  }
};
var CiscoCodePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.styleEl = null;
    this.refreshTimer = null;
  }
  async onload() {
    console.log("Loading Cisco Code Highlighter");
    await this.loadSettings();
    this.processor = new HighlightProcessor(this.settings);
    this.injectStyles();
    this.registerMarkdownCodeBlockProcessor(
      "cisco",
      (source, el, ctx) => {
        this.processCodeBlock(source, el);
      }
    );
    this.registerMarkdownCodeBlockProcessor(
      "ios",
      (source, el, ctx) => {
        this.processCodeBlock(source, el);
      }
    );
    this.addCommand({
      id: "insert-cisco-block",
      name: "Insert Cisco code block",
      editorCallback: (editor) => {
        editor.replaceSelection("```cisco\n\n```");
        const cursor = editor.getCursor();
        editor.setCursor(cursor.line - 1, 0);
      }
    });
    this.addRibbonIcon("terminal", "Insert Cisco code block", () => {
      const activeLeaf = this.app.workspace.activeLeaf;
      if (activeLeaf) {
        const view = activeLeaf.view;
        if (view instanceof import_obsidian.MarkdownView) {
          view.editor.replaceSelection("```cisco\n\n```");
          const cursor = view.editor.getCursor();
          view.editor.setCursor(cursor.line - 1, 0);
        }
      }
    });
    this.addSettingTab(new CiscoSettingTab(this.app, this));
    console.log("Cisco Code Highlighter loaded successfully");
  }
  onunload() {
    console.log("Unloading Cisco Code Highlighter");
    if (this.styleEl) {
      this.styleEl.remove();
    }
    if (this.refreshTimer) {
      window.clearTimeout(this.refreshTimer);
    }
  }
  async loadSettings() {
    const loadedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loadedData);
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.processor.updateSettings(this.settings);
    this.injectStyles();
    if (this.refreshTimer) {
      window.clearTimeout(this.refreshTimer);
    }
    this.refreshTimer = window.setTimeout(() => {
      this.refreshPreviews();
    }, 100);
  }
  processCodeBlock(source, el) {
    try {
      if (source.length > 5e4) {
        console.warn("Code block too large, truncating");
        source = source.substring(0, 5e4) + "\n... (truncated)";
      }
      const container = el.createDiv({ cls: "cisco-block" });
      if (this.settings.lineNumbers) {
        container.addClass("has-line-numbers");
      }
      const lines = source.split("\n");
      const maxLines = Math.min(lines.length, 1e3);
      for (let i = 0; i < maxLines; i++) {
        const line = lines[i];
        const lineEl = container.createDiv({ cls: "cisco-line" });
        if (this.settings.lineNumbers) {
          lineEl.createSpan({
            cls: "line-number",
            text: String(i + 1).padStart(3, " ")
          });
        }
        const contentSpan = lineEl.createSpan({ cls: "cisco-content" });
        contentSpan.innerHTML = this.processor.processLine(line);
      }
      if (this.settings.debugMode) {
        console.log(`Processed code block: ${maxLines} lines`);
      }
    } catch (error) {
      console.error("Error processing Cisco code block:", error);
      el.createDiv({
        text: "Error highlighting code block",
        cls: "cisco-block-error"
      });
    }
  }
  injectStyles() {
    if (this.styleEl) {
      this.styleEl.remove();
    }
    this.styleEl = document.createElement("style");
    this.styleEl.id = "cisco-highlight-styles";
    this.styleEl.textContent = this.processor.generateCSS();
    document.head.appendChild(this.styleEl);
  }
  refreshPreviews() {
    try {
      this.app.workspace.iterateAllLeaves((leaf) => {
        if (leaf.view.getViewType() === "markdown") {
          const view = leaf.view;
          if (view.preview && view.preview.rerender) {
            requestAnimationFrame(() => {
              try {
                view.preview.rerender(true);
              } catch (e) {
                console.error("Error refreshing preview:", e);
              }
            });
          }
        }
      });
    } catch (error) {
      console.error("Error refreshing previews:", error);
    }
  }
};
